name: Publish Website over SFTP

on:
    workflow_run:
        workflows: ['Linting JavaScript, and CSS.']
        types: [completed]

jobs:
    after:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - run: echo "Second action successfully finished!"
